# Generated by Django 5.1.2 on 2024-10-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeeHistory',
            new_name='Fee',
        ),
    ]
