# Generated by Django 5.1.2 on 2024-10-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('class_name', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
    ]
